### ISSUE TITLE
Example auto-merge in a workflow

### ISSUE THREAD

**Issue by netserf** [netserf/github-actions-fun#60]
The example will use a snippet like this:

```
merge:
  if: github.actor == 'netserf'
  needs: [lint, test]
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1

  - uses: hmarr/auto-approve-action@v2.0.0
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  - uses: managedkaos/merge-pull-request@v1.2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
